-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 27, 2024 at 02:32 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `khoaluan_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `product_cars`
--

CREATE TABLE `product_cars` (
  `product_id` int(11) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_slug` varchar(255) NOT NULL,
  `product_price` bigint(20) NOT NULL,
  `product_thumbnail` text NOT NULL,
  `product_content` text NOT NULL,
  `manufacture_year` int(11) NOT NULL,
  `type_gearbox` varchar(255) NOT NULL,
  `code` varchar(255) NOT NULL,
  `product_status` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_end` timestamp NULL DEFAULT NULL,
  `categories_company_id` int(11) NOT NULL,
  `city_area_id` int(11) NOT NULL,
  `account_id` int(11) NOT NULL,
  `vehicles_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `product_cars`
--

INSERT INTO `product_cars` (`product_id`, `product_name`, `product_slug`, `product_price`, `product_thumbnail`, `product_content`, `manufacture_year`, `type_gearbox`, `code`, `product_status`, `created_at`, `created_end`, `categories_company_id`, `city_area_id`, `account_id`, `vehicles_id`) VALUES
(72, 'MAZDA 3', 'mazda-3', 650000001, '1719217380mazda-3-thumbnail.jpg', 'BÁN XE MAZDA 3 2018\r\n\r\nThông tin chi tiết:\r\n\r\n- Năm sản xuất: 2018\r\n- Số km đã đi: 60,000 km\r\n- Màu sắc: Trắng\r\n- Tình trạng: Xe không có tai nạn, không ngập nước. Xe được bảo dưỡng định kỳ tại hãng Mazda.\r\n- Động cơ: SkyActiv-G 1.5L, 4 xy-lanh thẳng hàng\r\n- Công suất cực đại: 110 mã lực tại 6,000 vòng/phút\r\n- Mô-men xoắn cực đại: 144 Nm tại 4,000 vòng/phút\r\n- Hộp số: Tự động 6 cấp\r\n- Dẫn động: Cầu trước (FWD)\r\n- Tiêu thụ nhiên liệu: Khoảng 5.9 lít/100 km (đường hỗn hợp)\r\n\r\nTrang bị và tiện nghi:\r\n\r\n- Hệ thống giải trí: Màn hình cảm ứng 7 inch, hỗ trợ Apple CarPlay và Android Auto, hệ thống âm thanh 6 loa.\r\n- An toàn: Hệ thống cảnh báo điểm mù, phanh ABS, hỗ trợ phanh khẩn cấp EBA, cân bằng điện tử DSC.\r\n- Nội thất: Ghế da cao cấp, ghế lái chỉnh điện 6 hướng, điều hòa tự động 1 vùng.\r\n- Ngoại thất: Đèn pha LED, đèn LED ban ngày, mâm xe hợp kim 16 inch.\r\n\r\nLý do bán: Không còn nhu cầu sử dụng, muốn đổi sang xe khác.\r\n\r\nGiá bán: 650 triệu VND (có thương lượng).\r\n\r\nLiên hệ: 0912345678 (Anh Tuấn)\r\n\r\nXe Mazda 3 2018 là lựa chọn tuyệt vời cho những ai muốn sở hữu một chiếc sedan hiện đại, tiết kiệm nhiên liệu và an toàn. Xe đã được chăm sóc kỹ lưỡng và bảo dưỡng định kỳ, đảm bảo hoạt động ổn định và bền bỉ. Hãy liên hệ ngay để xem xe và trải nghiệm trực tiếp!', 2018, '1', '579947', 2, '2024-06-27 12:16:33', '2024-12-19 17:00:00', 20, 59, 11, 1),
(73, 'MITSUBISHI TRITON', 'mitsubishi-triton', 750000000, '1719217810mitsubishi-triton-thumbnail.jpg', 'BÁN XE MITSUBISHI TRITON 2019\r\n\r\nThông tin chi tiết:\r\n\r\n- Năm sản xuất: 2019\r\n- Số km đã đi: 50,000 km\r\n- Màu sắc: Xám\r\n- Tình trạng: Xe không có tai nạn, không ngập nước. Xe còn mới, bảo dưỡng định kỳ tại hãng Mitsubishi.\r\n- Động cơ: 2.4L MIVEC Turbo Diesel, 4 xy-lanh thẳng hàng\r\n- Công suất cực đại: 181 mã lực tại 3,500 vòng/phút\r\n- Mô-men xoắn cực đại: 430 Nm tại 2,500 vòng/phút\r\n- Hộp số: Tự động 6 cấp\r\n- Dẫn động: 2 cầu (4WD)\r\n- Tiêu thụ nhiên liệu: Khoảng 8.5 lít/100 km (đường hỗn hợp)\r\n\r\nTrang bị và tiện nghi:\r\n\r\n- Hệ thống giải trí: Màn hình cảm ứng 7 inch, hỗ trợ Apple CarPlay và Android Auto, hệ thống âm thanh 6 loa.\r\n- An toàn: Hệ thống cảnh báo điểm mù, phanh ABS, hỗ trợ phanh khẩn cấp BA, cân bằng điện tử ASC, hệ thống kiểm soát lực kéo, cảm biến lùi, camera lùi.\r\n- Nội thất: Ghế da cao cấp, ghế lái chỉnh điện 8 hướng, điều hòa tự động 2 vùng, hàng ghế sau gập linh hoạt.\r\n- Ngoại thất: Đèn pha LED, đèn LED ban ngày, mâm xe hợp kim 18 inch, bệ bước chân, nắp thùng sau thể thao.\r\n\r\nLý do bán: Không còn nhu cầu sử dụng, muốn đổi sang xe khác.\r\n\r\nGiá bán: 750 triệu VND (có thương lượng).\r\n\r\nLiên hệ: 0912345678 (Anh Tuấn)\r\n\r\nXe Mitsubishi Triton 2019 là lựa chọn tuyệt vời cho những ai cần một chiếc bán tải mạnh mẽ, đa dụng và tiết kiệm nhiên liệu. Xe đã được chăm sóc kỹ lưỡng và bảo dưỡng định kỳ, đảm bảo hoạt động ổn định và bền bỉ. Hãy liên hệ ngay để xem xe và trải nghiệm trực tiếp!', 2019, '1', '661559', 2, '2024-06-27 12:16:29', '2024-07-06 17:00:00', 22, 59, 12, 2),
(74, 'Mazda CX-5', 'mazda-cx-5', 850000000, '1719228830thumbnail_CX-5.jpg', '<p>&nbsp;</p>\r\n\r\n<p><br />\r\nTh&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2019<br />\r\n- Số km đ&atilde; đi: 45,000 km<br />\r\n- M&agrave;u sắc: Đỏ<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mazda.<br />\r\n- Động cơ: SkyActiv-G 2.0L, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 153 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 200 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 6 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.8 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh Bose 10 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, cảnh b&aacute;o chệch l&agrave;n đường, phanh khẩn cấp tự động, cảm biến l&ugrave;i, camera 360 độ.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 8 hướng, ghế phụ chỉnh điện 4 hướng, điều h&ograve;a tự động 2 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 19 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 850 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Văn B)</p>\r\n\r\n<p>Xe Mazda CX-5 2019 n&agrave;y l&agrave; lựa chọn ho&agrave;n hảo cho gia đ&igrave;nh hoặc c&aacute; nh&acirc;n muốn sở hữu một chiếc SUV mạnh mẽ, tiện nghi v&agrave; an to&agrave;n. Xe đ&atilde; được chăm s&oacute;c cẩn thận v&agrave; lu&ocirc;n bảo dưỡng định kỳ, đảm bảo hoạt động tốt v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2019, '1', '172390', 1, '2024-06-27 12:16:19', NULL, 20, 59, 10, 1),
(75, 'MAZDA CX-30', 'mazda-cx-30', 820000000, '1719228899cx-30-thumbnail.jpg', '<p>B&Aacute;N XE MAZDA CX-30 2020</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 25,000 km<br />\r\n- M&agrave;u sắc: Xanh dương<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mazda.<br />\r\n- Động cơ: SkyActiv-G 2.0L, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 155 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 200 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 6 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.5 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 8.8 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 8 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, cảnh b&aacute;o chệch l&agrave;n đường, phanh khẩn cấp tự động, cảm biến l&ugrave;i, camera 360 độ.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 8 hướng, điều h&ograve;a tự động 2 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 18 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 820 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Mazda CX-30 2020 l&agrave; sự lựa chọn ho&agrave;n hảo cho những ai muốn sở hữu một chiếc SUV nhỏ gọn, hiện đại v&agrave; an to&agrave;n. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2020, '2', '2977993', 1, '2024-06-27 12:16:35', NULL, 20, 59, 10, 2),
(76, 'MAZDA CX-30', 'mazda-cx-30', 500000000, '1719228970cx-30-thumbnail.jpg', '<p>B&Aacute;N XE MAZDA CX-30 2017</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 25,000 km<br />\r\n- M&agrave;u sắc: Xanh dương<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mazda.<br />\r\n- Động cơ: SkyActiv-G 2.0L, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 155 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 200 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 6 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.5 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 8.8 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 8 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, cảnh b&aacute;o chệch l&agrave;n đường, phanh khẩn cấp tự động, cảm biến l&ugrave;i, camera 360 độ.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 8 hướng, điều h&ograve;a tự động 2 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 18 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 50 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Văn B)</p>\r\n\r\n<p>Xe Mazda CX-30 2020 l&agrave; sự lựa chọn ho&agrave;n hảo cho những ai muốn sở hữu một chiếc SUV nhỏ gọn, hiện đại v&agrave; an to&agrave;n. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2017, '3', '9667909', 1, '2024-06-24 11:36:10', NULL, 20, 40, 10, 3),
(77, 'MAZDA 3', 'mazda-3', 650000000, '1719229041mazda-3-thumbnail.jpg', '<p>B&Aacute;N XE MAZDA 3 2018</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2018<br />\r\n- Số km đ&atilde; đi: 60,000 km<br />\r\n- M&agrave;u sắc: Trắng<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe được bảo dưỡng định kỳ tại h&atilde;ng Mazda.<br />\r\n- Động cơ: SkyActiv-G 1.5L, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 110 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 144 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 6 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 5.9 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 6 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, phanh ABS, hỗ trợ phanh khẩn cấp EBA, c&acirc;n bằng điện tử DSC.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 6 hướng, điều h&ograve;a tự động 1 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 16 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 650 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Văn B)</p>\r\n\r\n<p>Xe Mazda 3 2018 l&agrave; lựa chọn tuyệt vời cho những ai muốn sở hữu một chiếc sedan hiện đại, tiết kiệm nhi&ecirc;n liệu v&agrave; an to&agrave;n. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2018, '4', '5778873', 1, '2024-06-27 12:14:54', NULL, 20, 59, 10, 1),
(78, 'MAZDA 6', 'mazda-6', 950000000, '1719229091mazda-6-thumbnail.jpg', '<p>B&Aacute;N XE MAZDA 6 2019</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2019<br />\r\n- Số km đ&atilde; đi: 35,000 km<br />\r\n- M&agrave;u sắc: Đen<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mazda.<br />\r\n- Động cơ: SkyActiv-G 2.5L, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 188 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 252 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 6 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 7.5 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 8 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh Bose 11 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, cảnh b&aacute;o chệch l&agrave;n đường, phanh khẩn cấp tự động, cảm biến l&ugrave;i, camera 360 độ.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 10 hướng, ghế phụ chỉnh điện 6 hướng, điều h&ograve;a tự động 2 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 19 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 950 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Mazda 6 2019 l&agrave; sự kết hợp ho&agrave;n hảo giữa hiệu suất mạnh mẽ, thiết kế sang trọng v&agrave; c&aacute;c c&ocirc;ng nghệ an to&agrave;n hiện đại. Xe đ&atilde; được chăm s&oacute;c cẩn thận v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động tốt v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2019, '1', '3262974', 1, '2024-06-24 11:38:11', NULL, 20, 16, 10, 2),
(79, 'HONDA CITY', 'honda-city', 580000000, '1719232734honda-city-thumbnail.jpg', 'BÁN XE HONDA CITY 2020\r\n\r\nThông tin chi tiết:\r\n\r\n- Năm sản xuất: 2020\r\n- Số km đã đi: 30,000 km\r\n- Màu sắc: Bạc\r\n- Tình trạng: Xe không có tai nạn, không ngập nước. Xe còn mới, bảo dưỡng định kỳ tại hãng Honda.\r\n- Động cơ: 1.5L i-VTEC, 4 xy-lanh thẳng hàng\r\n- Công suất cực đại: 118 mã lực tại 6,600 vòng/phút\r\n- Mô-men xoắn cực đại: 145 Nm tại 4,600 vòng/phút\r\n- Hộp số: Tự động vô cấp CVT\r\n- Dẫn động: Cầu trước (FWD)\r\n- Tiêu thụ nhiên liệu: Khoảng 5.8 lít/100 km (đường hỗn hợp)\r\n\r\nTrang bị và tiện nghi:\r\n\r\n- Hệ thống giải trí: Màn hình cảm ứng 8 inch, hỗ trợ Apple CarPlay và Android Auto, hệ thống âm thanh 8 loa.\r\n- An toàn: Hệ thống cảnh báo điểm mù, phanh ABS, hỗ trợ phanh khẩn cấp BA, cân bằng điện tử VSA, túi khí đôi trước.\r\n- Nội thất: Ghế da cao cấp, ghế lái chỉnh điện 6 hướng, điều hòa tự động 1 vùng.\r\n- Ngoại thất: Đèn pha LED, đèn LED ban ngày, mâm xe hợp kim 16 inch.\r\n\r\nLý do bán: Không còn nhu cầu sử dụng, muốn đổi sang xe khác.\r\n\r\nGiá bán: 580 triệu VND (có thương lượng).\r\n\r\nLiên hệ: 0912345678 (Anh Tuấn)\r\n\r\nXe Honda City 2020 là lựa chọn lý tưởng cho những ai muốn sở hữu một chiếc sedan nhỏ gọn, tiết kiệm nhiên liệu và đáng tin cậy. Xe đã được chăm sóc cẩn thận và bảo dưỡng định kỳ, đảm bảo hoạt động ổn định và bền bỉ. Hãy liên hệ ngay để xem xe và trải nghiệm trực tiếp!', 2020, '2', '294239', 2, '2024-06-24 12:39:21', '2024-12-19 17:00:00', 8, 64, 11, 2),
(80, 'HONDA CITY', 'honda-city', 580000000, '1719488642honda-city-thumbnail.jpg', '<p>B&Aacute;N XE HONDA CITY 2020</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 30,000 km<br />\r\n- M&agrave;u sắc: Bạc<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Honda.<br />\r\n- Động cơ: 1.5L i-VTEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 118 m&atilde; lực tại 6,600 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 145 Nm tại 4,600 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động v&ocirc; cấp CVT<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 5.8 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 8 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 8 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử VSA, t&uacute;i kh&iacute; đ&ocirc;i trước.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 6 hướng, điều h&ograve;a tự động 1 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 16 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 580 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Honda City 2020 l&agrave; lựa chọn l&yacute; tưởng cho những ai muốn sở hữu một chiếc sedan nhỏ gọn, tiết kiệm nhi&ecirc;n liệu v&agrave; đ&aacute;ng tin cậy. Xe đ&atilde; được chăm s&oacute;c cẩn thận v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2020, '1', '537550', 1, '2024-06-27 11:44:02', NULL, 8, 10, 9, 1),
(81, 'HONDA CIVIC', 'honda-civic', 720000000, '1719488778honda-civic-thumbnail.jpg', '<p>B&Aacute;N XE HONDA CIVIC 2019</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2019<br />\r\n- Số km đ&atilde; đi: 40,000 km<br />\r\n- M&agrave;u sắc: X&aacute;m<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Honda.<br />\r\n- Động cơ: 1.8L i-VTEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 141 m&atilde; lực tại 6,500 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 174 Nm tại 4,300 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động v&ocirc; cấp CVT<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.2 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 8 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử VSA, cảm biến l&ugrave;i, camera l&ugrave;i.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 8 hướng, điều h&ograve;a tự động 2 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 17 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 720 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Honda Civic 2019 l&agrave; sự kết hợp ho&agrave;n hảo giữa hiệu suất, thiết kế hiện đại v&agrave; c&aacute;c c&ocirc;ng nghệ an to&agrave;n ti&ecirc;n tiến. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2019, '1', '2446698', 1, '2024-06-27 12:14:50', NULL, 8, 59, 9, 1),
(82, 'HONDA CIVIC', 'honda-civic', 650000000, '1719488841honda-civic-thumbnail.jpg', '<p>B&Aacute;N XE HONDA CIVIC 2017</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2019<br />\r\n- Số km đ&atilde; đi: 40,000 km<br />\r\n- M&agrave;u sắc: X&aacute;m<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Honda.<br />\r\n- Động cơ: 1.8L i-VTEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 141 m&atilde; lực tại 6,500 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 174 Nm tại 4,300 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động v&ocirc; cấp CVT<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.2 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 8 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử VSA, cảm biến l&ugrave;i, camera l&ugrave;i.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 8 hướng, điều h&ograve;a tự động 2 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 17 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 650 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Honda Civic 2019 l&agrave; sự kết hợp ho&agrave;n hảo giữa hiệu suất, thiết kế hiện đại v&agrave; c&aacute;c c&ocirc;ng nghệ an to&agrave;n ti&ecirc;n tiến. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2017, '2', '2438018', 1, '2024-06-27 11:47:21', NULL, 8, 67, 9, 2),
(83, 'HONDA CIVIC RS', 'honda-civic-rs', 870000000, '1719489050honda-civic-rs-thumbnail.jpg', '<p>B&Aacute;N XE HONDA CIVIC RS 2020</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 20,000 km<br />\r\n- M&agrave;u sắc: Đỏ<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Honda.<br />\r\n- Động cơ: 1.5L VTEC Turbo, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 170 m&atilde; lực tại 5,500 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 220 Nm tại 1,700 - 5,500 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động v&ocirc; cấp CVT<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.0 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 10 loa cao cấp.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử VSA, cảm biến l&ugrave;i, camera l&ugrave;i, cảnh b&aacute;o va chạm ph&iacute;a trước, hỗ trợ giữ l&agrave;n đường.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 8 hướng, điều h&ograve;a tự động 2 v&ugrave;ng, cửa sổ trời.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 18 inch, c&aacute;nh lướt gi&oacute; thể thao.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 870 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Honda Civic RS 2020 l&agrave; phi&ecirc;n bản thể thao cao cấp với hiệu suất vượt trội, thiết kế năng động v&agrave; nhiều c&ocirc;ng nghệ ti&ecirc;n tiến. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2020, '3', '9562308', 1, '2024-06-27 11:50:50', NULL, 8, 13, 9, 2),
(84, 'HONDA CIVIC RS', 'honda-civic-rs', 669000000, '1719489124honda-civic-rs-thumbnail.jpg', '<p>B&Aacute;N XE HONDA CIVIC RS 2018</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 20,000 km<br />\r\n- M&agrave;u sắc: Đỏ<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Honda.<br />\r\n- Động cơ: 1.5L VTEC Turbo, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 170 m&atilde; lực tại 5,500 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 220 Nm tại 1,700 - 5,500 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động v&ocirc; cấp CVT<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.0 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 10 loa cao cấp.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử VSA, cảm biến l&ugrave;i, camera l&ugrave;i, cảnh b&aacute;o va chạm ph&iacute;a trước, hỗ trợ giữ l&agrave;n đường.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 8 hướng, điều h&ograve;a tự động 2 v&ugrave;ng, cửa sổ trời.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 18 inch, c&aacute;nh lướt gi&oacute; thể thao.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 669 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Honda Civic RS 2020 l&agrave; phi&ecirc;n bản thể thao cao cấp với hiệu suất vượt trội, thiết kế năng động v&agrave; nhiều c&ocirc;ng nghệ ti&ecirc;n tiến. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2018, '1', '5594052', 1, '2024-06-27 11:52:04', NULL, 8, 66, 9, 3),
(85, 'MITSUBISHI XFORCE', 'mitsubishi-xforce', 720000000, '1719489241mitsubishi-xforce-thumbnail.jpg', '<p>B&Aacute;N XE MITSUBISHI XFORCE 2018</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2021<br />\r\n- Số km đ&atilde; đi: 15,000 km<br />\r\n- M&agrave;u sắc: Trắng<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mitsubishi.<br />\r\n- Động cơ: 1.5L MIVEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 105 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 141 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động v&ocirc; cấp CVT<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 7.0 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 8 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 6 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử ASC, cảm biến l&ugrave;i, camera l&ugrave;i.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 6 hướng, điều h&ograve;a tự động 2 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 17 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 720 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Mitsubishi Xforce 2021 l&agrave; sự kết hợp ho&agrave;n hảo giữa hiệu suất ổn định, thiết kế hiện đại v&agrave; c&aacute;c c&ocirc;ng nghệ an to&agrave;n ti&ecirc;n tiến. Xe đ&atilde; được chăm s&oacute;c cẩn thận v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2018, '3', '928799', 1, '2024-06-27 11:54:01', NULL, 22, 51, 9, 3),
(86, 'MITSUBISHI XFORCE', 'mitsubishi-xforce', 450000000, '1719489319mitsubishi-xforce-thumbnail.jpg', '<p>B&Aacute;N XE MITSUBISHI XFORCE 2015</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2021<br />\r\n- Số km đ&atilde; đi: 15,000 km<br />\r\n- M&agrave;u sắc: Trắng<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mitsubishi.<br />\r\n- Động cơ: 1.5L MIVEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 105 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 141 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động v&ocirc; cấp CVT<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 7.0 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 8 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 6 loa.<br />\r\n- An to&agrave;n: Hệ thống cảnh b&aacute;o điểm m&ugrave;, phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử ASC, cảm biến l&ugrave;i, camera l&ugrave;i.<br />\r\n- Nội thất: Ghế da cao cấp, ghế l&aacute;i chỉnh điện 6 hướng, điều h&ograve;a tự động 2 v&ugrave;ng.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 17 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 450 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Mitsubishi Xforce 2021 l&agrave; sự kết hợp ho&agrave;n hảo giữa hiệu suất ổn định, thiết kế hiện đại v&agrave; c&aacute;c c&ocirc;ng nghệ an to&agrave;n ti&ecirc;n tiến. Xe đ&atilde; được chăm s&oacute;c cẩn thận v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2015, '4', '333219', 1, '2024-06-27 11:55:19', NULL, 22, 52, 9, 2),
(87, 'MITSUBISHI XPANDER', 'mitsubishi-xpander', 620000000, '1719489392mitsubishi-xpander-thumbnail.jpg', '<p>B&Aacute;N XE MITSUBISHI XPANDER 2019</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 35,000 km<br />\r\n- M&agrave;u sắc: Bạc<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mitsubishi.<br />\r\n- Động cơ: 1.5L MIVEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 104 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 141 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 4 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.9 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 6 loa.<br />\r\n- An to&agrave;n: Hệ thống phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử ASC, hệ thống kiểm so&aacute;t lực k&eacute;o, t&uacute;i kh&iacute; đ&ocirc;i trước, cảm biến l&ugrave;i, camera l&ugrave;i.<br />\r\n- Nội thất: Ghế da, ghế l&aacute;i chỉnh tay 6 hướng, điều h&ograve;a tự động 2 v&ugrave;ng, h&agrave;ng ghế thứ 3 gập linh hoạt.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 16 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 620 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Mitsubishi Xpander 2020 l&agrave; sự lựa chọn l&yacute; tưởng cho gia đ&igrave;nh với kh&ocirc;ng gian rộng r&atilde;i, tiện nghi v&agrave; tiết kiệm nhi&ecirc;n liệu. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2019, '1', '2829082', 1, '2024-06-27 12:14:46', NULL, 22, 59, 9, 2),
(88, 'MITSUBISHI XPANDER', 'mitsubishi-xpander', 720000000, '1719489434mitsubishi-xpander-thumbnail.jpg', '<p>B&Aacute;N XE MITSUBISHI XPANDER 2020</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 35,000 km<br />\r\n- M&agrave;u sắc: Bạc<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mitsubishi.<br />\r\n- Động cơ: 1.5L MIVEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 104 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 141 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 4 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.9 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 6 loa.<br />\r\n- An to&agrave;n: Hệ thống phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử ASC, hệ thống kiểm so&aacute;t lực k&eacute;o, t&uacute;i kh&iacute; đ&ocirc;i trước, cảm biến l&ugrave;i, camera l&ugrave;i.<br />\r\n- Nội thất: Ghế da, ghế l&aacute;i chỉnh tay 6 hướng, điều h&ograve;a tự động 2 v&ugrave;ng, h&agrave;ng ghế thứ 3 gập linh hoạt.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 16 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 620 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Mitsubishi Xpander 2020 l&agrave; sự lựa chọn l&yacute; tưởng cho gia đ&igrave;nh với kh&ocirc;ng gian rộng r&atilde;i, tiện nghi v&agrave; tiết kiệm nhi&ecirc;n liệu. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2020, '1', '6618225', 1, '2024-06-27 12:14:43', NULL, 22, 59, 9, 2),
(89, 'MITSUBISHI XPANDER', 'mitsubishi-xpander', 600000000, '1719489478Mitsubishi-Xpander-front.jpg', '<p>B&Aacute;N XE MITSUBISHI XPANDER 2019</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 35,000 km<br />\r\n- M&agrave;u sắc: Bạc<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mitsubishi.<br />\r\n- Động cơ: 1.5L MIVEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 104 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 141 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 4 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.9 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 6 loa.<br />\r\n- An to&agrave;n: Hệ thống phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử ASC, hệ thống kiểm so&aacute;t lực k&eacute;o, t&uacute;i kh&iacute; đ&ocirc;i trước, cảm biến l&ugrave;i, camera l&ugrave;i.<br />\r\n- Nội thất: Ghế da, ghế l&aacute;i chỉnh tay 6 hướng, điều h&ograve;a tự động 2 v&ugrave;ng, h&agrave;ng ghế thứ 3 gập linh hoạt.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 16 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 620 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Mitsubishi Xpander 2020 l&agrave; sự lựa chọn l&yacute; tưởng cho gia đ&igrave;nh với kh&ocirc;ng gian rộng r&atilde;i, tiện nghi v&agrave; tiết kiệm nhi&ecirc;n liệu. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2019, '3', '9652761', 1, '2024-06-27 11:57:58', NULL, 22, 59, 9, 5),
(90, 'MITSUBISHI XPANDER', 'mitsubishi-xpander', 720000000, '1719489585mitsubishi-xpander-thumbnail.jpg', '<p>B&Aacute;N XE MITSUBISHI XPANDER 2020</p>\r\n\r\n<p>Th&ocirc;ng tin chi tiết:</p>\r\n\r\n<p>- Năm sản xuất: 2020<br />\r\n- Số km đ&atilde; đi: 35,000 km<br />\r\n- M&agrave;u sắc: Bạc<br />\r\n- T&igrave;nh trạng: Xe kh&ocirc;ng c&oacute; tai nạn, kh&ocirc;ng ngập nước. Xe c&ograve;n mới, bảo dưỡng định kỳ tại h&atilde;ng Mitsubishi.<br />\r\n- Động cơ: 1.5L MIVEC, 4 xy-lanh thẳng h&agrave;ng<br />\r\n- C&ocirc;ng suất cực đại: 104 m&atilde; lực tại 6,000 v&ograve;ng/ph&uacute;t<br />\r\n- M&ocirc;-men xoắn cực đại: 141 Nm tại 4,000 v&ograve;ng/ph&uacute;t<br />\r\n- Hộp số: Tự động 4 cấp<br />\r\n- Dẫn động: Cầu trước (FWD)<br />\r\n- Ti&ecirc;u thụ nhi&ecirc;n liệu: Khoảng 6.9 l&iacute;t/100 km (đường hỗn hợp)</p>\r\n\r\n<p>Trang bị v&agrave; tiện nghi:</p>\r\n\r\n<p>- Hệ thống giải tr&iacute;: M&agrave;n h&igrave;nh cảm ứng 7 inch, hỗ trợ Apple CarPlay v&agrave; Android Auto, hệ thống &acirc;m thanh 6 loa.<br />\r\n- An to&agrave;n: Hệ thống phanh ABS, hỗ trợ phanh khẩn cấp BA, c&acirc;n bằng điện tử ASC, hệ thống kiểm so&aacute;t lực k&eacute;o, t&uacute;i kh&iacute; đ&ocirc;i trước, cảm biến l&ugrave;i, camera l&ugrave;i.<br />\r\n- Nội thất: Ghế da, ghế l&aacute;i chỉnh tay 6 hướng, điều h&ograve;a tự động 2 v&ugrave;ng, h&agrave;ng ghế thứ 3 gập linh hoạt.<br />\r\n- Ngoại thất: Đ&egrave;n pha LED, đ&egrave;n LED ban ng&agrave;y, m&acirc;m xe hợp kim 16 inch.</p>\r\n\r\n<p>L&yacute; do b&aacute;n: Kh&ocirc;ng c&ograve;n nhu cầu sử dụng, muốn đổi sang xe kh&aacute;c.</p>\r\n\r\n<p>Gi&aacute; b&aacute;n: 620 triệu VND (c&oacute; thương lượng).</p>\r\n\r\n<p>Li&ecirc;n hệ: 0912345678 (Anh Tuấn)</p>\r\n\r\n<p>Xe Mitsubishi Xpander 2020 l&agrave; sự lựa chọn l&yacute; tưởng cho gia đ&igrave;nh với kh&ocirc;ng gian rộng r&atilde;i, tiện nghi v&agrave; tiết kiệm nhi&ecirc;n liệu. Xe đ&atilde; được chăm s&oacute;c kỹ lưỡng v&agrave; bảo dưỡng định kỳ, đảm bảo hoạt động ổn định v&agrave; bền bỉ. H&atilde;y li&ecirc;n hệ ngay để xem xe v&agrave; trải nghiệm trực tiếp!</p>', 2020, '1', '7711059', 1, '2024-06-27 11:59:45', NULL, 22, 59, 10, 2);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `product_cars`
--
ALTER TABLE `product_cars`
  ADD PRIMARY KEY (`product_id`),
  ADD KEY `categories_company_id` (`categories_company_id`),
  ADD KEY `account_id` (`account_id`),
  ADD KEY `city_area_id` (`city_area_id`),
  ADD KEY `product_cars_ibfk_3` (`vehicles_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `product_cars`
--
ALTER TABLE `product_cars`
  MODIFY `product_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=91;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `product_cars`
--
ALTER TABLE `product_cars`
  ADD CONSTRAINT `product_cars_ibfk_1` FOREIGN KEY (`categories_company_id`) REFERENCES `categories_company` (`id`),
  ADD CONSTRAINT `product_cars_ibfk_2` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`),
  ADD CONSTRAINT `product_cars_ibfk_3` FOREIGN KEY (`vehicles_id`) REFERENCES `vehicles` (`id`),
  ADD CONSTRAINT `product_cars_ibfk_4` FOREIGN KEY (`city_area_id`) REFERENCES `citys` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
